// bin2c: walks a list of input directories tagged by slice, emits a single
// C++ source that defines the byte arrays + slice manifest consumed by
// EmbeddedTemplate.cpp / GameBuilder.
//
// Usage:
//   bin2c <output.cpp> [--slice native-linux <dir>] [--slice native-windows <dir>] [--slice web <dir>]
//
// Slices that aren't passed in are emitted as empty arrays so the editor can
// still link and probe `hasSlice()` at runtime.

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

struct Slice
{
    std::string name;   // canonical slice id: "native-linux", "native-windows", "web"
    std::string root;   // directory to walk (may be empty)
};

static std::vector<unsigned char> readBinary(const fs::path &p)
{
    std::ifstream f(p, std::ios::binary);
    std::vector<unsigned char> out;
    if (!f) return out;
    f.seekg(0, std::ios::end);
    auto sz = f.tellg();
    f.seekg(0, std::ios::beg);
    out.resize(static_cast<size_t>(sz));
    if (sz > 0) f.read(reinterpret_cast<char *>(out.data()), sz);
    return out;
}

static std::string forwardSlashes(const std::string &s)
{
    std::string r = s;
    for (auto &c : r) if (c == '\\') c = '/';
    return r;
}

// Walk a directory tree and collect (relative-path, absolute-path) pairs.
static std::vector<std::pair<std::string, fs::path>> walk(const fs::path &root)
{
    std::vector<std::pair<std::string, fs::path>> files;
    if (root.empty() || !fs::exists(root)) return files;
    for (auto &entry : fs::recursive_directory_iterator(root))
    {
        if (!entry.is_regular_file()) continue;
        auto rel = fs::relative(entry.path(), root);
        files.emplace_back(forwardSlashes(rel.generic_string()), entry.path());
    }
    return files;
}

static void emitArray(std::ofstream &out, const std::string &symbol,
                      const std::vector<unsigned char> &bytes)
{
    out << "static const unsigned char " << symbol << "[] = {";
    constexpr int kPerLine = 16;
    for (size_t i = 0; i < bytes.size(); ++i)
    {
        if ((i % kPerLine) == 0) out << "\n    ";
        char buf[8];
        std::snprintf(buf, sizeof(buf), "0x%02x,", static_cast<unsigned>(bytes[i]));
        out << buf;
    }
    out << "\n};\n";
}

int main(int argc, char **argv)
{
    if (argc < 2)
    {
        std::fprintf(stderr, "usage: bin2c <out.cpp> [--slice <name> <dir>]...\n");
        return 1;
    }
    std::string outPath = argv[1];

    std::vector<Slice> slices = {
        {"native-linux",   ""},
        {"native-windows", ""},
        {"web",            ""},
    };

    for (int i = 2; i + 2 < argc + 1; )
    {
        std::string flag = argv[i];
        if (flag != "--slice")
        {
            std::fprintf(stderr, "bin2c: unexpected arg '%s'\n", flag.c_str());
            return 1;
        }
        if (i + 2 >= argc)
        {
            std::fprintf(stderr, "bin2c: --slice needs <name> <dir>\n");
            return 1;
        }
        std::string sliceName = argv[i + 1];
        std::string sliceDir = argv[i + 2];
        bool found = false;
        for (auto &s : slices)
            if (s.name == sliceName) { s.root = sliceDir; found = true; break; }
        if (!found)
        {
            std::fprintf(stderr, "bin2c: unknown slice '%s'\n", sliceName.c_str());
            return 1;
        }
        i += 3;
    }

    std::ofstream out(outPath, std::ios::binary);
    if (!out)
    {
        std::fprintf(stderr, "bin2c: cannot write %s\n", outPath.c_str());
        return 1;
    }

    out << "// Auto-generated by bin2c. Do not edit.\n";
    out << "#include \"EmbeddedTemplate.hpp\"\n";
    out << "namespace {\n";

    // Per-slice file table: (relPath, dataSymbol, size)
    struct EmittedFile { std::string relPath; std::string symbol; size_t size; };
    std::vector<std::vector<EmittedFile>> tables(slices.size());

    int counter = 0;
    for (size_t si = 0; si < slices.size(); ++si)
    {
        const Slice &s = slices[si];
        auto files = walk(s.root);
        for (auto &[rel, abs] : files)
        {
            auto bytes = readBinary(abs);
            std::string sym = "kBlob_" + std::to_string(counter++);
            emitArray(out, sym, bytes);
            tables[si].push_back({rel, sym, bytes.size()});
        }
    }

    for (size_t si = 0; si < slices.size(); ++si)
    {
        std::string sanitized = slices[si].name;
        for (auto &c : sanitized) if (c == '-') c = '_';
        out << "static const EmbeddedFile kFiles_" << sanitized << "[] = {";
        if (tables[si].empty()) out << "\n    {nullptr, nullptr, 0}";
        for (auto &f : tables[si])
        {
            out << "\n    {\"" << f.relPath << "\", " << f.symbol << ", " << f.size << "},";
        }
        out << "\n};\n";
        out << "static const std::size_t kFiles_" << sanitized << "_count = "
            << tables[si].size() << ";\n";
    }

    out << "} // namespace\n\n";
    out << "bool EmbeddedTemplate_hasSlice(EmbeddedSlice s) {\n";
    out << "    switch (s) {\n";
    out << "    case EmbeddedSlice::NativeLinux:   return kFiles_native_linux_count > 0;\n";
    out << "    case EmbeddedSlice::NativeWindows: return kFiles_native_windows_count > 0;\n";
    out << "    case EmbeddedSlice::Web:           return kFiles_web_count > 0;\n";
    out << "    }\n    return false;\n}\n\n";

    out << "std::size_t EmbeddedTemplate_fileCount(EmbeddedSlice s) {\n";
    out << "    switch (s) {\n";
    out << "    case EmbeddedSlice::NativeLinux:   return kFiles_native_linux_count;\n";
    out << "    case EmbeddedSlice::NativeWindows: return kFiles_native_windows_count;\n";
    out << "    case EmbeddedSlice::Web:           return kFiles_web_count;\n";
    out << "    }\n    return 0;\n}\n\n";

    out << "EmbeddedFile EmbeddedTemplate_fileAt(EmbeddedSlice s, std::size_t i) {\n";
    out << "    switch (s) {\n";
    out << "    case EmbeddedSlice::NativeLinux:   return kFiles_native_linux[i];\n";
    out << "    case EmbeddedSlice::NativeWindows: return kFiles_native_windows[i];\n";
    out << "    case EmbeddedSlice::Web:           return kFiles_web[i];\n";
    out << "    }\n    return {nullptr, nullptr, 0};\n}\n";

    return 0;
}
