#!/usr/bin/env python3
"""
Simple OBJ -> engine mesh converter

Outputs either a JSON mesh (vertices, indices) or a C++ header with arrays.

Usage:
  python3 scripts/obj_to_mesh.py input.obj -o out.json
  python3 scripts/obj_to_mesh.py input.obj --format hpp -o mesh_name.hpp

JSON format keys: vertices (flat float array), indices (uint array),
vertex_stride (3 pos + optional 3 normal + optional 2 uv)
"""
import sys
import os
import argparse
import json


def parse_obj(path):
    verts = []
    norms = []
    uvs = []
    faces = []

    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            if not line or line[0] == '#':
                continue
            parts = line.strip().split()
            if not parts:
                continue
            if parts[0] == 'v':
                verts.append(tuple(float(x) for x in parts[1:4]))
            elif parts[0] == 'vn':
                norms.append(tuple(float(x) for x in parts[1:4]))
            elif parts[0] == 'vt':
                uvs.append(tuple(float(x) for x in parts[1:3]))
            elif parts[0] == 'f':
                # faces can have 3 or more vertices; store each polygon as list of vertex refs
                face = []
                for v in parts[1:]:
                    # v form: v, v/vt, v//vn, v/vt/vn
                    refs = v.split('/')
                    vi = int(refs[0]) - 1 if refs[0] else None
                    vti = int(refs[1]) - 1 if len(refs) > 1 and refs[1] else None
                    vni = int(refs[2]) - 1 if len(refs) > 2 and refs[2] else None
                    face.append((vi, vti, vni))
                faces.append(face)
    return verts, uvs, norms, faces


def build_mesh(verts, uvs, norms, faces):
    # build unique vertex list mapping (v,vt,vn) -> idx
    vertex_map = {}
    vertex_list = []  # flat list of floats
    indices = []

    has_uv = len(uvs) > 0
    has_n = len(norms) > 0

    for face in faces:
        # triangulate polygons with fan method
        if len(face) < 3:
            continue
        tri_refs = []
        for i in range(1, len(face)-1):
            tri_refs.append((face[0], face[i], face[i+1]))

        for tri in tri_refs:
            for ref in tri:
                key = ref
                if key in vertex_map:
                    indices.append(vertex_map[key])
                else:
                    vi, vti, vni = key
                    px, py, pz = verts[vi]
                    vertex_components = [px, py, pz]
                    if has_n:
                        if vni is not None:
                            nx, ny, nz = norms[vni]
                        else:
                            nx, ny, nz = (0.0, 0.0, 0.0)
                        vertex_components += [nx, ny, nz]
                    if has_uv:
                        if vti is not None:
                            u, v = uvs[vti]
                        else:
                            u, v = (0.0, 0.0)
                        vertex_components += [u, v]

                    idx = len(vertex_map)
                    vertex_map[key] = idx
                    indices.append(idx)
                    vertex_list.extend(vertex_components)

    stride = 3 + (3 if has_n else 0) + (2 if has_uv else 0)
    return vertex_list, indices, stride, has_n, has_uv


def write_json(out_path, vertices, indices, stride, has_n, has_uv):
    data = {
        'vertex_stride': stride,
        'has_normals': bool(has_n),
        'has_uv': bool(has_uv),
        'vertices': vertices,
        'indices': indices,
    }
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)


def write_hpp(out_path, varname, vertices, indices, stride):
    guard = os.path.basename(out_path).upper().replace('.', '_') + '_'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Generated by obj_to_mesh.py\n')
        f.write('#pragma once\n\n')
        f.write('static const float {}_vertices[] = {{\n'.format(varname))
        for i in range(0, len(vertices), stride):
            row = ', '.join(f'{v:.6f}f' for v in vertices[i:i+stride])
            f.write('  ' + row + ',\n')
        f.write('};\n\n')
        f.write('static const unsigned int {}_indices[] = {{\n'.format(varname))
        for i in range(0, len(indices), 16):
            chunk = ', '.join(str(x) for x in indices[i:i+16])
            f.write('  ' + chunk + ',\n')
        f.write('};\n\n')
        f.write('static const unsigned int {}_vertex_count = {};\n'.format(varname, len(vertices)//stride))
        f.write('static const unsigned int {}_index_count = {};\n'.format(varname, len(indices)))


def main():
    parser = argparse.ArgumentParser(description='Convert OBJ to engine mesh (JSON or HPP)')
    parser.add_argument('input', help='Input OBJ file')
    parser.add_argument('-o', '--out', help='Output file (default: input.json)', default=None)
    parser.add_argument('--format', choices=['json', 'hpp'], default='json')
    parser.add_argument('--var', help='C++ variable prefix when using hpp', default='mesh')
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print('Input file not found:', args.input)
        sys.exit(2)

    verts, uvs, norms, faces = parse_obj(args.input)
    vertices, indices, stride, has_n, has_uv = build_mesh(verts, uvs, norms, faces)

    out = args.out
    if not out:
        base = os.path.splitext(os.path.basename(args.input))[0]
        out = base + ('.json' if args.format == 'json' else '.hpp')

    if args.format == 'json':
        write_json(out, vertices, indices, stride, has_n, has_uv)
        print('Wrote JSON mesh to', out)
    else:
        write_hpp(out, args.var, vertices, indices, stride)
        print('Wrote C++ header to', out)


if __name__ == '__main__':
    main()
