#include "GameBuilder.hpp"
#include "Scene.hpp"
#include "EmbeddedTemplate.hpp"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#endif

#if defined(_WIN32) && !defined(__EMSCRIPTEN__)
#include <windows.h>
#include <shlobj.h>
#endif

// Game HTML shell generated by GameBuilder for every web export.
// Kept here so it's always fresh — the pre-built HTML in the game template bundle
// is old and does not carry the scene-injection hook.
// The sentinel "var __COWENGINE_SCENE__ = null;" is replaced at export time with
// "var __COWENGINE_SCENE__ = atob('BASE64SCENE');" so the correct scene loads.
static const char kGameHtmlTemplate[] =
R"html(<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>CowEngine Game</title>
    <style>
        html,body{height:100%;margin:0;background:#000;color:#eee;font-family:Arial,sans-serif;overflow:hidden;}
        body{display:flex;flex-direction:column;}
        #main{position:relative;flex:1 1 auto;display:flex;}
        #canvas{display:block;width:100%;height:100%;background:#000;outline:none;}
        .overlay{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;text-align:center;}
        #loadingOverlay{background:#000;z-index:40;flex-direction:column;}
        #startOverlay{background:rgba(0,0,0,0.6);z-index:30;cursor:pointer;font-size:22px;color:#fff;}
        #startOverlay .hint{font-size:14px;color:#bbb;margin-top:12px;}
    </style>
</head>
<body>
    <div id="main">
        <canvas id="canvas" tabindex="0"></canvas>
        <div id="loadingOverlay" class="overlay">
            <div>
                <div style="font-size:24px;margin-bottom:12px;">Loading...</div>
                <div style="font-size:13px;color:#888;">Decompressing assets</div>
            </div>
        </div>
        <div id="startOverlay" class="overlay" style="display:none;">
            <div>
                <div>Click to play</div>
                <div class="hint">WASD to move, mouse to look, Space to jump, Tab to release cursor</div>
            </div>
        </div>
    </div>
    <script>
        var __COWENGINE_SCENE__ = null;
        // Write the exported scene to localStorage before CowEngine.js loads so the
        // C++ localStorage mechanism picks it up without any EM_ASM global reads.
        if (typeof __COWENGINE_SCENE__ === 'string' && __COWENGINE_SCENE__) {
            try { localStorage.setItem('cowengine_save', __COWENGINE_SCENE__); } catch(e) {}
        }
        function resizeCanvas(){
            var c=document.getElementById('canvas');if(!c)return;
            var r=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;
            if(document.fullscreenElement===c){w=window.innerWidth;h=window.innerHeight;}
            c.width=Math.max(1,Math.floor(w*r));c.height=Math.max(1,Math.floor(h*r));
            if(typeof Module!=='undefined'&&Module)Module.canvas=c;
        }
        document.addEventListener('DOMContentLoaded',resizeCanvas);
        window.addEventListener('resize',resizeCanvas);
        document.addEventListener('fullscreenchange',resizeCanvas);
        var Module={
            noInitialRun:false,
            canvas:(function(){return document.getElementById('canvas');})(),
            print:function(){console.log.apply(console,arguments);},
            printErr:function(){console.error.apply(console,arguments);},
            onRuntimeInitialized:function(){
                Module.mouseSensitivity=1.0;
                document.getElementById('loadingOverlay').style.display='none';
                var s=document.getElementById('startOverlay');
                s.style.display='flex';
                var c=document.getElementById('canvas');
                c.addEventListener('contextmenu',function(e){e.preventDefault();});
                function go(){s.style.display='none';c.focus();if(c.requestPointerLock)c.requestPointerLock();}
                s.addEventListener('click',go);
                resizeCanvas();
            }
        };
    </script>
    <script async src="CowEngine.js"></script>
</body>
</html>)html";

namespace
{
    // Standard base64 encode — used to safely embed the scene JSON into HTML.
    std::string base64Encode(const std::string &input)
    {
        static const char table[] =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        std::string out;
        out.reserve(((input.size() + 2) / 3) * 4);
        for (std::size_t i = 0; i < input.size(); i += 3)
        {
            auto b0 = (unsigned char)input[i];
            auto b1 = i + 1 < input.size() ? (unsigned char)input[i + 1] : 0;
            auto b2 = i + 2 < input.size() ? (unsigned char)input[i + 2] : 0;
            out += table[b0 >> 2];
            out += table[((b0 & 3) << 4) | (b1 >> 4)];
            out += i + 1 < input.size() ? table[((b1 & 15) << 2) | (b2 >> 6)] : '=';
            out += i + 2 < input.size() ? table[b2 & 63] : '=';
        }
        return out;
    }

    // Replace the __COWENGINE_SCENE__ sentinel in HTML bytes with the base64-encoded scene.
    void patchHtmlScene(std::vector<unsigned char> &htmlBytes, const std::string &sceneJson)
    {
        const std::string marker = "var __COWENGINE_SCENE__ = null;";
        std::string html(htmlBytes.begin(), htmlBytes.end());
        auto pos = html.find(marker);
        if (pos == std::string::npos)
            return;
        std::string replacement = "var __COWENGINE_SCENE__ = atob('" + base64Encode(sceneJson) + "');";
        html.replace(pos, marker.size(), replacement);
        htmlBytes.assign(html.begin(), html.end());
    }

    // Build a fresh game HTML blob from the embedded template, patched with the scene.
    std::vector<unsigned char> makeGameHtml(const std::string &sceneJson)
    {
        std::vector<unsigned char> html(kGameHtmlTemplate,
                                        kGameHtmlTemplate + std::strlen(kGameHtmlTemplate));
        if (!sceneJson.empty())
            patchHtmlScene(html, sceneJson);
        return html;
    }

    // Pick which target maps to which slice of the embedded template archive.
    // In this build the editor only embeds the host-matching native template plus
    // the web template (the latter only when produced by the build).
    EmbeddedSlice sliceForTarget(GameBuilder::Target t)
    {
        switch (t)
        {
        case GameBuilder::Target::Linux:
            return EmbeddedSlice::NativeLinux;
        case GameBuilder::Target::Windows:
            return EmbeddedSlice::NativeWindows;
        case GameBuilder::Target::Web:
            return EmbeddedSlice::Web;
        }
        return EmbeddedSlice::NativeLinux;
    }

#if !defined(__EMSCRIPTEN__)
    // Cross-platform native folder picker. Returns empty string on cancel.
    std::string pickFolderNative()
    {
        auto fallbackPath = []() -> std::string
        {
#if defined(_WIN32)
            const char *home = std::getenv("USERPROFILE");
            if (!home || !*home)
                home = std::getenv("HOMEPATH");
#else
            const char *home = std::getenv("HOME");
#endif
            if (!home || !*home)
                return "";
            return std::string(home) + "/CowEngineBuilds";
        };
#if defined(_WIN32)
        BROWSEINFOA bi{};
        bi.lpszTitle = "Choose destination folder for game build";
        bi.ulFlags = BIF_USENEWUI | BIF_RETURNONLYFSDIRS;
        LPITEMIDLIST pidl = SHBrowseForFolderA(&bi);
        if (!pidl)
            return "";
        char path[MAX_PATH] = {};
        if (!SHGetPathFromIDListA(pidl, path))
            return "";
        CoTaskMemFree(pidl);
        return std::string(path);
#elif defined(__APPLE__)
        // osascript-based directory chooser
        FILE *p = popen("osascript -e 'POSIX path of (choose folder with prompt \"Choose destination folder for game build\")' 2>/dev/null", "r");
        if (!p)
            return "";
        char buf[4096] = {};
        std::string out;
        while (fgets(buf, sizeof(buf), p))
            out.append(buf);
        pclose(p);
        while (!out.empty() && (out.back() == '\n' || out.back() == '\r'))
            out.pop_back();
        return out;
#else
        // Linux: try zenity then kdialog
        auto try_cmd = [](const char *cmd) -> std::string
        {
            FILE *p = popen(cmd, "r");
            if (!p)
                return "";
            char buf[4096] = {};
            std::string out;
            while (fgets(buf, sizeof(buf), p))
                out.append(buf);
            int rc = pclose(p);
            if (rc != 0)
                return "";
            while (!out.empty() && (out.back() == '\n' || out.back() == '\r'))
                out.pop_back();
            return out;
        };
        std::string r = try_cmd("zenity --file-selection --directory --title='Choose destination folder for game build' 2>/dev/null");
        if (!r.empty())
            return r;
        r = try_cmd("kdialog --getexistingdirectory ~ --title 'Choose destination folder for game build' 2>/dev/null");
        if (!r.empty())
            return r;
        return fallbackPath();
#endif
    }
#endif

    // Write a file (creating parent dirs).
    bool writeBlob(const std::filesystem::path &outPath, const unsigned char *bytes, std::size_t size,
                   std::string &err)
    {
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::create_directories(outPath.parent_path(), ec);
        std::ofstream f(outPath, std::ios::binary);
        if (!f)
        {
            err = "cannot open for write: " + outPath.string();
            return false;
        }
        f.write(reinterpret_cast<const char *>(bytes), static_cast<std::streamsize>(size));
        return static_cast<bool>(f);
    }

    // Serialize current scene + on-disk scripts/scene as a flat in-memory list of
    // {relativePath, bytes}. Used by the web zip path.
    void stageSceneSnapshot(Scene *scene, std::vector<StagedFile> &out)
    {
        if (!scene)
            return;
        // Save the live scene to a temp file we can read back as bytes.
        namespace fs = std::filesystem;
        std::error_code ec;
        fs::path tmpDir = fs::temp_directory_path(ec);
        if (ec || tmpDir.empty())
            tmpDir = ".";
        fs::path tmp = tmpDir / "cowengine_build_scene.json";
        fs::create_directories(tmp.parent_path(), ec);
        if (!scene->saveToJSON(tmp.string()))
            return;
        std::ifstream f(tmp, std::ios::binary);
        if (!f)
            return;
        std::ostringstream ss;
        ss << f.rdbuf();
        std::string s = ss.str();
        StagedFile sf;
        sf.path = "scenes/scene.json";
        sf.bytes.assign(s.begin(), s.end());
        out.push_back(std::move(sf));
    }
} // namespace

bool GameBuilder::isTargetAvailable(Target t)
{
#if defined(__EMSCRIPTEN__)
    // Web editor can only export web builds.
    return t == Target::Web;
#else
    // A target is available if an embedded slice for it exists.
    return EmbeddedTemplate_hasSlice(sliceForTarget(t));
#endif
}

const char *GameBuilder::targetLabel(Target t)
{
    switch (t)
    {
    case Target::Linux:
        return "Linux Game...";
    case Target::Windows:
        return "Windows Game...";
    case Target::Web:
        return "Web Game (.zip)...";
    }
    return "?";
}

GameBuilder::Result GameBuilder::build(Target t, Scene *scene,
                                       const std::function<void(const std::string &)> &log)
{
    Result r;
    auto say = [&](const std::string &m)
    { if (log) log(m); };

    if (!isTargetAvailable(t))
    {
        r.message = "Target not available on this platform.";
        return r;
    }

    EmbeddedSlice slice = sliceForTarget(t);
    std::size_t count = EmbeddedTemplate_fileCount(slice);

#if defined(__EMSCRIPTEN__)
    // Web: build a flat list of {path, bytes} and hand it to JS for zipping + download.
    // The JS side is provided by EmbeddedTemplate_jsDownloadZip (declared in
    // EmbeddedTemplate.hpp).
    if (count == 0)
    {
        r.message = "Web template missing. Build game-web and rebuild the editor.";
        return r;
    }
    say("Packaging web build...");
    std::vector<StagedFile> staged;
    for (std::size_t i = 0; i < count; ++i)
    {
        EmbeddedFile ef = EmbeddedTemplate_fileAt(slice, i);
        StagedFile sf;
        sf.path = ef.relativePath;
        sf.bytes.assign(ef.data, ef.data + ef.size);
        staged.push_back(std::move(sf));
    }
    stageSceneSnapshot(scene, staged);
    // Generate a fresh index.html / CowEngine.html from the embedded template with the
    // current scene baked in. buildStoredZip keeps the last occurrence of each path,
    // so these entries replace whatever HTML was in the pre-built game-web bundle.
    {
        std::string sceneJson;
        for (const auto &sf : staged)
        {
            if (sf.path == "scenes/scene.json")
            {
                sceneJson.assign(sf.bytes.begin(), sf.bytes.end());
                break;
            }
        }
        auto freshHtml = makeGameHtml(sceneJson);
        StagedFile si, sc;
        si.path = "index.html";    si.bytes = freshHtml;
        sc.path = "CowEngine.html"; sc.bytes = freshHtml;
        staged.push_back(std::move(si));
        staged.push_back(std::move(sc));
    }
    EmbeddedTemplate_jsDownloadZip(staged, "CowEngineGame.zip");
    r.ok = true;
    r.message = "Download started (CowEngineGame.zip)";
    return r;
#else
    std::string dir = pickFolderNative();
    if (dir.empty())
    {
        r.message = "Cancelled.";
        return r;
    }
    namespace fs = std::filesystem;
    fs::path root(dir);
    // Drop our payload into a clearly-named subfolder so we never blow away
    // unrelated files in the user's chosen directory.
    fs::path target = root / "CowEngineGame";
    std::error_code ec;
    fs::create_directories(target, ec);
    say("Writing build to " + target.string());

    std::string err;
    for (std::size_t i = 0; i < count; ++i)
    {
        EmbeddedFile ef = EmbeddedTemplate_fileAt(slice, i);
        if (!writeBlob(target / ef.relativePath, ef.data, ef.size, err))
        {
            r.message = err;
            return r;
        }
    }

    // Overlay the user's current in-memory scene last so it wins over any
    // scene baked into the template.
    std::string sceneJson;
    if (scene)
    {
        fs::path sceneDest = target / "scenes" / "scene.json";
        if (scene->saveToJSON(sceneDest.string()))
        {
            say("Wrote live scene.json");
            std::ifstream sf(sceneDest, std::ios::binary);
            if (sf)
            {
                std::ostringstream ss;
                ss << sf.rdbuf();
                sceneJson = ss.str();
            }
        }
    }
    // Generate a fresh index.html / CowEngine.html from the embedded template with the
    // current scene baked in. This overwrites whatever HTML the template bundle wrote.
    {
        auto freshHtml = makeGameHtml(sceneJson);
        for (auto name : {"index.html", "CowEngine.html"})
        {
            std::ofstream f(target / name, std::ios::binary);
            f.write(reinterpret_cast<const char *>(freshHtml.data()), freshHtml.size());
        }
        if (!sceneJson.empty())
            say("Injected scene into index.html");
    }

    r.ok = true;
    r.message = target.string();
    return r;
#endif
}
