name: Deploy static content to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3 git

      - name: Install and activate EMSDK, build web
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd $GITHUB_WORKSPACE
          emcmake cmake --preset game-web
          cmake --build --preset game-web -j
          cmake --install build/game-web
          emcmake cmake --preset editor-web
          cmake --build --preset editor-web -j
          cmake --install build/editor-web
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload dist/editor-web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/editor-web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
